{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-breakdown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/breakDown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/breakDown/breakDown_{{ version }}.tar.gz
  sha256: 384d1fc8ccfb21c29a89dabb67d38c5bd7432019138c75beac295be67cfda9ca

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('breakDown')"           # [not win]
    - "\"%R%\" -e \"library('breakDown')\""  # [win]

about:
  home: https://pbiecek.github.io/breakDown/
  license: GPL-2.0-only
  summary: 'Model agnostic tool for decomposition of predictions from black boxes. Break Down Table shows contributions of every variable to a final prediction.  Break Down Plot presents variable contributions in a concise graphical way.  This package work for binary classifiers and general regression models. '
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
