{% set version = "0.1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-breakdown
  version: {{ version|replace("-", "_") }}

source:
  fn: breakDown_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/breakDown_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/breakDown/breakDown_{{ version }}.tar.gz
  sha256: 82ca18c8f14605d7bbcca9a59ae3b77976f2e0ec1744c71f9f575f2f48bb3455

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2
    - r-ranger

  run:
    - r-base
    - r-ggplot2
    - r-ranger

test:
  commands:
    - $R -e "library('breakDown')"  # [not win]
    - "\"%R%\" -e \"library('breakDown')\""  # [win]

about:
  home: https://pbiecek.github.io/breakDown/
  license: GPL-2
  summary: "Break Down Plots are inspired by waterfall plots created by 'xgboostExplainer' package
    (see <https://github.com/AppliedDataSciencePartners/xgboostExplainer>). The idea behind Break
    Down Plots it to decompose model prediction for a single observation. Break Down Plots show the
    contribution of every variable present in the model. Such plots will work for binary classifiers
    and general regression models."
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
