# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R33FUbWopZ7Iv3a5Bh78U+jD2467r6I2FKVgH1k1Wm5f7JeGW+oWSDGSx0lFKOlEH/abQ5GARtFOhXcUNaXPTetadyO+x2g9F6SF05i2hJWh9pG4gb4tRqVNjZPbELELwKu1fwdlKmlUMvFRAvdgrLgbNMhU1RO44i6ohoiMgJhJLXGwDnW1/X5Wv8iwRDypRv0d+rCr+CKh5VFw8zcCFwRxlYZ4KlQEwrJ20+5p7y84SOTp2Kh/EFFNH4Fjsi0bXMWg5GcpRC5q/0D5bgzG+lvxthDTMce1Q8bOXOuKo2I5AU95RdnpBlAmCSZS1jD6Z1KMasqB6QzncY4S4IavpTs7RTK0AXgynDRLmbuIYZSQT4/eoBJinLSg+Uo+UWEctgJOywGapvLk4Oya+lXCTDFwcL4Qn77dKL95uKO954KVcbMivWwhBIvskWZbyDgcT4KLEafDafosDUfyONIdIsuWVzM0hAzOCTh4tMU7RCAmVsOSMiB8cyEFl0XyubgLBfi+WtlFYbtGnXUnW1wFBjz2/ikGQe/uP9ZmYEA6OFn5LKZrbw2OAJRUPMBn3qwZHvb03X84LN1PNvleDSdG5Fn4Wg4EwuHdOxBjRolx7TI1XiqwMQXx6LPCxkDO00pgFFdGQGWJKYbXuTp1qbiPrD9Ff5UXeg77Fnct1y2Z7J0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
