travis:
  secure:
    BINSTAR_TOKEN: QtX1PnpuxCutVkBElXeC1kl3jnCoC1zo7pv7LiCEyikmL1D1CiUn4mIDLbdxo1y2/JFvSUrBd3dE2TTjbx9tEQEXdK46ydSytyED3L0BVx8buT7oTXoW+beEvQibdu3li3X5Deg37CDcNWiZHBW+DEMeLzNdBKYUgeYrsCxyOxfEwJgJ+ru81aXWzFPgAkb904KhH0TSHVlr4O5ton/HLVGTJlLctyzfS4k6NYWWXbwIw4VW8Xz7Boz2s3DsWd1gO+FGrAJ6mQPGQ77ks8+r/uqb1y1uADW7GAMfszNr6o8zXusvDLNSblNXJWAQoNxOuXy0SF4f1+DQFcnMeA6ZE2hJAKfwAvRFWAUAa2otNfmHf1Pxs2nT5uPI19BnBDfrzSSY+AG+eb60jMX+jBFv/Ms4H1AWoQCSrZApeZoPxa+MvFzsNZ+4Xgm3x5PXzAdy7jp8YsIv6KQdhqhLzj+2xy4hj3kBrTY7GID8RuILdPL7u8k55hJH3zvvu/jgtz4kyYqqejQ74q8Coieps/7Vbvj/Id58h1RKMtJw0IKz+fueAS4r21Ru+IDpoU0ccvVQR+Jj2UgllEvR6MmSZdnDCPaoJIUNmF38FT1TKEdCeImQo43iJzklN96WRIHzmJyA0lASi3wT1rls5D/1LwovRikJ1HByVm9KCBRejvm+jas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
