travis:
  secure:
    BINSTAR_TOKEN: TR1RCeKg8jd4tYcL2oaQ0CrDVWJZLuFrVUPZmaqK6cTjhWojWeRSvQvslnAElmtOi/gLLtkF7ZFZur+2+1fnccLwASfWIEgC0UaKXSM2f7bZfg1SzHy0tAC1+TcpkxYQMIhb9ketuBXSXfS8IS6DGeeiO/iC7YzU6xhA+HDO7PTCY+nuhxxh5az+J9nItY3U4E3WLQzY9nbCpbm7J1i8cmba3nxq2NVFON3b/Fgn/cw9vGjxU7J9dSOxzdVhOwx17bCagKc1nqbeyxcjdV2fnkTv377l1NcV78wps+5yE7odr8dVhNLTVx4nACrxBruNyADgDE2TJElNubYMUsanMFJnICJhxmNTIK2zHzQ4aTqRoUr6EWOLUPkgcT/ZmlgIbNH40vXWC7+gqaLfyLf8uEYq3yyY7WvaIjqh1xyaYMP70QmkDni+YuWKALsZAbJ1ufekLc1TpZ++FMCLsziq9pmTHb2rL9SRknsR1XK/Qm2NJLW29k8BovpGAv0Et9QIb+k1EFnDqFgT0ApINChM9bgN5c/pkfsX6UInpDYEJaQjdNUpIjq7vi8KMjPHLMwbkSyX7FQxgUqlL7dx5eWARNM9ohvP/IdKgaAsUo4R1WUz9prgLorT9kYf87OHclbfmP0qhQ6eKXDcQsF0hAtQhq249LVOLPJXteYqg51mnlI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
