travis:
  secure:
    BINSTAR_TOKEN: xgOAlfFs18gYJ1JzIDAHaHwgXyPKSXTFTvJ374LYADJ3irFgl2ukJ8LOJzAAFUOH7O9Q2nk5rbEzUwUDT+iEBYjfAtRu93siuDCT3i60zXcb9n9cY674+xpIvkDhFKufeKExNRofX+PFBM81xLOKO3M8xTNn79KwEP1k6udRcRxG3DgMRC2POs+IwxnV9zP4CX2xmTevDaudHOaYII4Dq6dBV8HifmKssGHdwve37YJuXL+vwrNJsXeTnAm0C7qSJBpryR7JaP2Ey+XFDnwTfR3Mh7kHEG0xdmQu9Op+vZrOrEQNFrimNeo4pHXQ3IsxUttjOWjSTheGMsI9reFyKe3oCdHUK3a9X8qVDNS00aF1SICeTJMXhV9umZmgG05lkHH8/jRgGSGUyYqX0Wmb4/D3k/tykqeM3mfWoBFxzzZ7OqnW+sD4iIUUpbLyRK3oGYS9t2NRsEl2iCNofxiqSfX3IfXXD4GYooUZEkvGjUwXHRpAN2F1DtEVD0tLPvsvXNGJvNALL+am9F8a4A14lnGV6vK9Fcr5BphmyE8i+IpgSw2qD3n/9hi1Cbetjk7gRF9u4yL45Ot8Kgg3yVTZaGg3eN3qmbrnUcEDGSa2+TImXNe/H1wNyTvENVdyZ83Yf5gvTB4j2jMp3joh6AOIkJU5WDPKYWo0sg6CWAKSYaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
